version: '3'
services:
  web:
    build: .
    container_name: ecommerce
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ecommerce
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE='database'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='some_password'
      - MYSQL_ROOT_PASSWORD='some_password'
      - MYSQL_HOST='db'
    volumes:
      - ./db:/var/lib/mysql